# NUMPY BASICS

# Intro to NumPy

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.




### install the numpy

In [ ]:
pip install numpy

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
print (a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a[0]))
print(a.data)
print(type(a))


1
10
4
int32
<class 'numpy.int32'>
<class 'numpy.ndarray'>


### Makes the processing faster


In [5]:
a =[1,2,3]
b =[4,5,6]
for i in range(len(a)):
    print(a[i]*b[i])

4
10
18


In [6]:
import numpy as np
a = np.arange(1,4)
print(a)
b =  np.arange(4,7)
print(b)
print(a*b)

[1 2 3]
[4 5 6]
[ 4 10 18]


 #### Import the numpy package

In [7]:
import numpy as np

In [8]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(10).reshape(2,5)
print (a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a))

2
10
4
int32
<class 'numpy.ndarray'>


In [22]:
import numpy as np

In [12]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
a = np.arange(10).reshape(2,5)
print (a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
a = np.arange(10).reshape(5,2)
print (a)
e =a.reshape(2,5)
print(e)
b = np.arange(10).reshape(5,2)
print(b)
c = b.reshape(1,10)
print(c)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4 5 6 7 8 9]]


In [30]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a))

2
10
4
int32
<class 'numpy.ndarray'>


#### using list to generate numpy array

In [17]:
b=np.array([2,3,4])
print(b)
print(b.dtype)

[2 3 4]
int32


In [16]:
d = b.reshape(3,1)
print(d)

[[2]
 [3]
 [4]]


In [18]:
c=np.array([[1,2],[3,4]])
print (c)

[[1 2]
 [3 4]]


In [19]:
c=np.array([[1,2],[3,4]],dtype='complex')
print (c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [20]:
c=np.array([[1,2],[3,4]],dtype='float')
print (c)

[[1. 2.]
 [3. 4.]]


In [23]:
t = np.arange(4).reshape(2,2)
print(t)

[[0 1]
 [2 3]]


In [24]:
t = np.arange(8).reshape(4,2)
print(t)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [22]:
t = np.arange(8).reshape(2,2,2)
print(t)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [21]:
t = np.arange(16).reshape(2,2,2,2)
print(t)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [23]:
print (t.ndim)
print(t.size)
print(t.itemsize)
print(t.dtype.name)

print(type(t))

4
16
4
int32
<class 'numpy.ndarray'>


### Generate Zeros

In [39]:
d=np.zeros([3,10])
print (d)
print(d.dtype.name)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64


In [44]:
e=np.empty([2,10])
print (e)

[[9.67844667e-312 6.27463370e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307 5.30276956e+180 3.31033942e-033 6.98205646e-076
  4.86764290e-086 3.35660025e-143]
 [6.01433264e+175 6.93885958e+218 5.56218858e+180 3.94356143e+180
  1.90187499e+185 2.12650137e+160 5.87717482e-062 3.83855214e+175
  4.45702949e-143 1.50008929e+248]]


In [20]:
##Range Functionalities

In [32]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
b=np.arange(10,30,5).reshape(2,2)
print (b)

[[10 15]
 [20 25]]


In [45]:
b=np.arange(10,36,5).reshape(3,2)#start, end, step
print (b)

[[10 15]
 [20 25]
 [30 35]]


In [40]:
c= np.linspace(10,30,4).reshape(2,2)#start, end, no of values required
print (c)

[[10.         16.66666667]
 [23.33333333 30.        ]]


In [48]:
c= np.linspace(10,22,12).reshape(3,4)#start, end, no of values required
print (c)

[[10.         11.09090909 12.18181818 13.27272727]
 [14.36363636 15.45454545 16.54545455 17.63636364]
 [18.72727273 19.81818182 20.90909091 22.        ]]


In [53]:
a = np.ones([2,3])
print (a)
c=np.array([[1,0,3],[4,0,6]])
print (c)


[[1. 1. 1.]
 [1. 1. 1.]]
[[1 0 3]
 [4 0 6]]
[[1. 0. 3.]
 [4. 0. 6.]]
[[1.                inf 0.33333333]
 [0.25              inf 0.16666667]]
[[ 1. nan  1.]
 [ 1. nan  1.]]


C:\Users\34320\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\34320\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in multiply
  if __name__ == '__main__':


In [ ]:
print(a*c)
InverseC  = a/c
print(InverseC)
print(c*InverseC)

In [54]:
b=np.random.random([3,3])
print (b)

[[0.88210652 0.18786928 0.67641038]
 [0.59124613 0.77788632 0.50614753]
 [0.10728285 0.78007762 0.31717636]]


In [41]:
b=np.random.random([2,3,4])
print (b)

[[[0.48814171 0.30033449 0.10192449 0.05485735]
  [0.12046971 0.73387673 0.22313211 0.94054139]
  [0.62945111 0.45237331 0.63668425 0.88375831]]

 [[0.12941171 0.34792585 0.07642056 0.04713886]
  [0.42530056 0.71822197 0.61671635 0.52500175]
  [0.92985978 0.61682837 0.44996284 0.75484195]]]


In [56]:
c=np.random.random([2,3])
print (c)
print ("sum of elements is ", c.sum())
print ("least elements is ",c.min())
print("largest of elements is ",c.max())
print("round  of elements is ",c.round(3))

[[0.60105528 0.34979573 0.15978316]
 [0.2708181  0.61759555 0.17533258]]
sum of elements is  2.1743803898638654
least elements is  0.1597831601969415
largest of elements is  0.6175955511880955
round  of elements is  [[0.601 0.35  0.16 ]
 [0.271 0.618 0.175]]


In [60]:
c=np.random.random([2,3])
print (c)
print("###########################")
print (c.sum())
print("###########################")
print (c.min())
print("###########################")
print(c.max())
print("###########################")
print(c.mean())
print("####### sum axis = 0####################")
print(c.sum(axis =0))
print("###########sum axis = 1################")
print(c.sum(axis =1))
print("###########cumulative sum axis = 0 ################")
print (c.cumsum(axis =0))
print("############cumulative sum axis = 1 ###############")
print (c.cumsum(axis =1))
print("###########################")

[[0.66435574 0.26788564 0.68382642]
 [0.95368953 0.50970054 0.96759296]]
###########################
4.0470508200011395
###########################
0.2678856379910942
###########################
0.9675929575523863
###########################
0.6745084700001899
####### sum axis = 0####################
[1.61804527 0.77758617 1.65141937]
###########sum axis = 1################
[1.61606779 2.43098303]
###########cumulative sum axis = 0 ################
[[0.66435574 0.26788564 0.68382642]
 [1.61804527 0.77758617 1.65141937]]
############cumulative sum axis = 1 ###############
[[0.66435574 0.93224138 1.61606779]
 [0.95368953 1.46339007 2.43098303]]
###########################


#### Make an array from a list. 

This will create a numpy array with 3 elements. 

Each numpy array contains an attribute called `shape`. Shape is a tuple which tells you how many elements you have per axis. For example (5, 6, 8) means 5 elements per axis 0, 6 elements per axis 1 and 8 elements per axis 2. Usually you will have only one or two axes.

The shape for the array in this section is `(3, )`. The reason for this funny notation is python's type system where shape must be a tuple and this is a tuple with 1 element. Writing just 3 would mean a number, not a tuple.

To verify that try `np.array([1, 2, 3]).shape` 

In [0]:
np.array([1, 2, 3])

#### Make an array from a list of lists

The shape of this array is (2, 2) so this is a matrix.

In [0]:
np.array([[1, 2], [3, 4]])

#### Make an array using a function

The arrays made in previous sections were based on us supplying each value.

Very often we need large arrays and it is not possible to use our current approach and thus we need to use array creating functions. The most important functions are `zeros` and `ones`. They both take a parameter called shape which determines the shape of the output array.
* `zeros` makes an array which is all 0 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
* `ones`  makes an array which is all 1 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

In [0]:
np.zeros((2, 3))

In [0]:
np.ones((3, 2))

#### Make an array by starting at 0, incrementing by 2 and ending before 10

`arange` is the exact same thing as regular python `range` except giving back a numpy array.

This functions requires only a single argument which is the end point. The start point is assumed to be 0 and step is assumed to be 1.

In this variety when in takes three parameters, the first one is the start, second one is the end and the third one is the step.

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [0]:
np.arange(0, 10, 2)

#### Make an array of four evenly spaced numbers including both endpoints

In [0]:
np.linspace(0, 1, 4)

#### Make an array of random numbers (using a normal distribution)

The random submodule of numpy contains a variety of functions for generating random numbers following a specified probability distributions or sampling from a finite set of choices. To learn more about it visit the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html). 

In [66]:
import numpy as np
mean = 10
stdev = 3
number_values = 20
resultant_array = np.random.normal(mean, stdev, number_values)
print(resultant_array )
print(resultant_array.mean())
print(resultant_array.std())
resultant_array = np.random.poisson(mean, stdev)
print(resultant_array )
print(resultant_array.mean())
print(resultant_array.std())

[10.68384718  8.7135841  13.41877743  8.73836252  7.33520872 10.03510093
  8.98130838  9.86886644 12.49598665  8.54345439  9.11703669  8.52092202
 11.0316153  10.9056931   9.84913584  5.11974367  9.75191804 15.84282719
 11.47932932  9.89086611]
10.016179202232019
2.2022461371170476
[14  7 11]
10.666666666666666
2.8674417556808756


## Indexing Arrays
#### Access elements of a 1-dimensional array.  Get the first and last element.

In python as is in many other programming languages all arrays start from 0 so the first element is at position 0.

To access the last element we can use -1 as the index. `x[-1]` is identical to `x[x.shape[0] - 1]` where `shape[0]` is the length of the array.

In [67]:
x = np.arange(4)

print(x[0])
print(x[-1])

0
3


In [71]:

x = np.linspace(10,20,10).reshape(2,5)
print(x)
#Get first row
print("##########################")
print(x[0])
print("##########################")
print(x[0][1])
print("##########################")
print(x[0][-1])
print("##########################")
print(x[1,-2])

[[10.         11.11111111 12.22222222 13.33333333 14.44444444]
 [15.55555556 16.66666667 17.77777778 18.88888889 20.        ]]
##########################
[10.         11.11111111 12.22222222 13.33333333 14.44444444]
##########################
11.11111111111111
##########################
14.444444444444445
##########################
18.88888888888889


In [72]:

x = np.linspace(10,20,30).reshape(2,5,3)
x = x.round(3)
print(x)
print("##########################")
#Get first row
print(x[0])
print("##########################")
print(x[0][1])
print("##########################")
print(x[0][-1])
print("##########################")
print(x[0,-1])

[[[10.    10.345 10.69 ]
  [11.034 11.379 11.724]
  [12.069 12.414 12.759]
  [13.103 13.448 13.793]
  [14.138 14.483 14.828]]

 [[15.172 15.517 15.862]
  [16.207 16.552 16.897]
  [17.241 17.586 17.931]
  [18.276 18.621 18.966]
  [19.31  19.655 20.   ]]]
##########################
[[10.    10.345 10.69 ]
 [11.034 11.379 11.724]
 [12.069 12.414 12.759]
 [13.103 13.448 13.793]
 [14.138 14.483 14.828]]
##########################
[11.034 11.379 11.724]
##########################
[14.138 14.483 14.828]
##########################
[14.138 14.483 14.828]


#### Reshape an array

Remember that shape is the fundamenal property of each array and we can modify it as we desire and we often do so. To change the shape of an array we use the `reshape` method.

The code in this example creates an 1D-array of 6 elements using the `arange` functon.

We convert it to a 2D-array using the `reshape` method.

You see that the total amount of numbers did not change, only our view of them. 6 elements in a vector or 3 x 2 elements in a matrix.

It is very important that when using `reshape` to ensure that dimensions match or you will get an error. 6 = 3 x 2 is a match so this works but trying np.arange(6).reshape(4, 2) will give you an error. 

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [0]:
x = np.arange(6).reshape(2, 3)
print(x)

#### Get the last row

When dealing with arrays which are of more than a single dimension we can use partial indexing specifications go slice the array the way we want. 

For example `print(x[-1])` will print the last **row**.

To get the last column take the transpose of the 2d-array and then use [-1]. 

For exampe `print(x.T[-1])` will give you the last columns. `x.T` is the transpose of `x`

In [0]:
print(x[-1])

#### Get the last element of the last row

Here we are using full indexing to get a single **element**.

In [14]:
print(x[-1, -1])

20.0


#### Get elements like a list

Using the notation `a:b` we can slice arrays as precisely as we want.

`a:b` means give me back all elements whose positions is in that set.

For example `y = [1, 3, 5, 7, 9]` and `y[0:2]` would give us the first two elements `[1, 3]`.

Negative indices mean from back so -3 means 3 positions starting from the last position.

Experiment with the values until you get the feel for it.

In [73]:
x = np.arange(10) 

print(x)
print(x[:3])
print(x[1:4])
print(x[-3:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2 3]
[7 8 9]


In [76]:
x = np.arange(27).reshape(3,3,3) 
print("######################")
print(x)
print("######################")
print(x[2:3])
print("######################")
print(x[1:2])
print("######################")
print(x[-3:])


######################
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
######################
[[[18 19 20]
  [21 22 23]
  [24 25 26]]]
######################
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
######################
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [110]:
print(x)
print("############################")
#print(x[:,::2,::2]) # Get all the corner values in the matrices
print("############################")
print(x[::-1,::-1,::-1]) # Get all the corner values in the matrices
print("############################")
print(x[:,::-1,::-1]) # Get all the corner values in the matrices
print("############################")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
############################
############################
[[[26 25 24]
  [23 22 21]
  [20 19 18]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]
############################
[[[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[26 25 24]
  [23 22 21]
  [20 19 18]]]
############################


#### Get all elements in reverse order

The enhanced slicing syntax is `a:b:c` were `c` is the step. For example `0:10:2`.

If we omit `a` and `b` we always asume they are `a` = 0 and `b` = length of the list so we are only left with a step.

Thus `::2` means slicing from 0 to end with a step 2. `::3` mean slicing with a step 3.

Now what if we used negative steps. Using -1 as the step would reverse the logic and `a` becomes the end of the list and `b` becomes zero. So `::-1` will slice in reverse direction.

Finally there is also the slice form `::1` or written short `:` which means give me back all elements in order as they are present.

In [23]:
print(x[::-1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [68]:
npreverse = np.arange(10).reshape(5,1,2)
print(npreverse)
print("##################### step =1")
print(npreverse[::1])
print("##################### step = 2")
print(npreverse[::2])
print("##################### step =-1")
print(npreverse[::-1])
print("##################### step =-2")
print(npreverse[::-2])

[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
##################### step =1
[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
##################### step = 2
[[[0 1]]

 [[4 5]]

 [[8 9]]]
##################### step =-1
[[[8 9]]

 [[6 7]]

 [[4 5]]

 [[2 3]]

 [[0 1]]]
##################### step =-2
[[[8 9]]

 [[4 5]]

 [[0 1]]]


#### Get every second element or third element

In [111]:
print(x[::2])
print(x[::3])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


#### Create a 5x5 matrix

In [114]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Get the first two columns and the first two rows

Until now you have learned how to slice on a 1D array but slices can be generalized to any dimensional arrays.

The trick is to create a slice for every dimensions. 

In this example we have a 2d-array so we create two slices, one for dimension 0 (rows) and one for dimension 1 (columns)


In [113]:
print(x[:2, :2])

[[0 1]
 [5 6]]


#### Get every second column of every second row

In [115]:
print(x[::2, ::2])

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


## Access parts of an array with index arrays

#### Generate six random integers between 0 and 9 inclusive

`randint` in `np.random` is a very useful function which generates uniformly distributed random integers from the range provided as its first two parameters (start and end of range respectively). It's third parameter tells the method how many numbers we need.

In [118]:
x = np.random.randint(0, 10, 6) 
print(x)

[5 1 5 4 4 9]


#### Get the first number and the last two numbers

Slices are inhetently linear and give us access to arrays in a linear fashion.

To access elements in any order we must use index arrays which are numpy arrays holding integer numbers which tell what elements to chose from the indexed array.

In [117]:
indices = [0, -2, -1]
print(x[indices])

[0 9 6]


In [129]:
b = np.random.randint(0,20,20).reshape(4,5)
print(b)

[[12 11  3 18 18]
 [14 18 16 12  2]
 [12  2  8  2 10]
 [16 12  4  5  9]]


In [137]:
indices = [0, -1]
print(b[indices])

indices_rows = [0, -1]
indices_cols = [1,2,4]
print(b[indices_rows,indices_cols])


[[12 11  3 18 18]
 [16 12  4  5  9]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

### Create two arrays

The array `x2` is created as `x1 * -1`. The multiplication operator here means multiply all elements of `x1` with -1 and give back that as result.

In [139]:
arrayLength = 5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1

print(x1)
print(x2)

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


#### Create a random shuffled range of numbers

This and the following example shows how to shuffle an array in numpy.

Shuffling means reordering the items in an array and we can do that using random permutations of the array positions.

In [150]:
arrayLength = 5
indices = np.random.permutation(arrayLength)
print(indices)

[0 4 3 1 2]


#### Use indices to re-order arrays

In [152]:
print(x1[indices])
print(x2[indices])

[0 4 3 1 2]
[ 0 -4 -3 -1 -2]


#### Create array of boolean values

The main novelty of this example is `print(x > 2)`.

`x > 2` generates an array of boolean values where each element is True or False.
Having True at position i of the output means that the conditions is satisfied for the element of `x` at position i.

For exampe if `x=[0,1,2,3,4]` then `x > 2` would be `[False, False, False, True, True]`.

As you see 0 > 2 = False, 1 > 2 = False, 2 > 2 = False, 3 > 2 = True and 4 > 2 = True and that is shown in the output array.

In [153]:
x = np.arange(5)
print(x)
print(x > 2)


[0 1 2 3 4]
[False False False  True  True]


In [154]:
indices = np.random.permutation(arrayLength)
print(indices)
print(indices > 3)

[0 3 2 1 4]
[False False False False  True]


#### Use boolean values to index arrays

Once we have created our boolean array we can use it to index other arrays.

The rule is very simple. If at position i of index we have True include `x[i]` in the output.

In [157]:
print(x > 2)
print("#######################################")
print(x[x > 2])
print("#######################################")
print(x[np.array([False,True,False,True,False])])

[False False False  True  True]
#######################################
[3 4]
#######################################
[1 3]


## Array Math

#### Try adding to a list

In [159]:
x = [1, 2, 3, 4]
#print(x*10)

print(x + 10)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

#### Try again with an array

When trying with a list you got an error because simple python lists do not support addition with scalars.

But numpy arrays do allow that.

In [164]:
x = np.array(x).reshape(2,2)

print(x)
print(x + 10)

print(x * 10)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[10 20]
 [30 40]]


### Finding Transpose -- converting rows and columns to the reverse


In [165]:
a = np.random.random([3,5])
print(a)
print("################## - Transpose")
b = a.transpose()
print(b)

[[0.23434762 0.86112282 0.83857384 0.80290126 0.57668189]
 [0.95529384 0.80863514 0.8554715  0.99752866 0.17815182]
 [0.33898262 0.48289208 0.35935187 0.74791567 0.44365743]]
################## - Transpose
[[0.23434762 0.95529384 0.33898262]
 [0.86112282 0.80863514 0.48289208]
 [0.83857384 0.8554715  0.35935187]
 [0.80290126 0.99752866 0.74791567]
 [0.57668189 0.17815182 0.44365743]]


In [168]:
u = np.eye(4)
#u = np.eye(4,2)
#u = np.eye(2)
print(u)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


    ##### Reading Data From Diskf

In [176]:
from io import StringIO
data = "1, 2, 3\n4, 5, 6"
data_1 = """1, 2, 3
4, 5, 6"""
array = np.genfromtxt(StringIO(data), delimiter=",")
print(array)
print("########################")
array1 = np.genfromtxt(StringIO(data_1), delimiter=",")
print(array1)

[[1. 2. 3.]
 [4. 5. 6.]]
########################
[[1. 2. 3.]
 [4. 5. 6.]]


In [180]:
data = "  1112  3\n  4 5 67\n890123 4"
array = np.genfromtxt(StringIO(data), delimiter=3)
print(array)

[[  1. 112.   3.]
 [  4.   5.  67.]
 [890. 123.   4.]]


In [48]:
#### Auto Stripping Values

In [181]:
data = "1, abc , 2\n 3, xxx, 4"
np.genfromtxt(StringIO(data), delimiter=",", dtype="|S5")

array([[b'1', b' abc ', b' 2'],
       [b'3', b' xxx', b' 4']], dtype='|S5')

In [193]:
data = """#
 # Skip me !
 # Skip me too !
 1,2
 1, 2
 3, 4
 5, 6 #This is the third line of the data
 7, 8
 # And here comes the last line
 9, 0
 """
print(np.genfromtxt(StringIO(data), comments="#", delimiter=","))


[[1. 2.]
 [1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]
 [9. 0.]]
####################################
[[1. 2.]
 [1. 2.]
 [3. 4.]]


In [200]:
data_1 = """#,
 $ Skip, me !
 1,2
 1, 2
 
 3, 4
 # Skip ,me too !
 5, 6 #This is the third line of the data
 7, 8
 # And here comes, the last line
 9, 0
 """
print("####################################")
print(np.genfromtxt(StringIO(data_1), comments ="$", delimiter=",", skip_header=3, skip_footer=3))
print(np.genfromtxt(StringIO(data_1), comments ="$", delimiter=",", skip_header=3, skip_footer=3))



####################################
[[ 1.  2.]
 [ 3.  4.]
 [nan nan]
 [ 5. nan]]
[[ 1.  2.]
 [ 3.  4.]
 [nan nan]
 [ 5. nan]]


In [201]:
data = "\n".join(str(i) for i in range(10))
print(data)
np.genfromtxt(StringIO(data),comments="#", skip_header=3, skip_footer=5)

0
1
2
3
4
5
6
7
8
9


array([3., 4.])

In [203]:
data = "\n".join("#" + str(i) for i in range(10))
print(data)
np.genfromtxt(StringIO(data),comments="#", skip_header=3, skip_footer=5)

#0
#1
#2
#3
#4
#5
#6
#7
#8
#9


C:\Users\34320\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x000001C81D2EB048>"
  This is separate from the ipykernel package so we can avoid doing imports until


array([], dtype=float64)

In [205]:
data = "1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), usecols=(0, -1))

array([[1., 3.],
       [4., 6.]])

## Exercises

#### Create an array from 0 to 26 assign it to a variable x

#### Reverse the order of the array and print it out

#### Convert the 1-dimensional array you created into a 3 dimensional array

#### Find the index (location) for value 12

#### Create a random shuffled list of values from 0-19 and assign it to variable y

#### Create an array of boolean values for values in y that are greater than 10

#### Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5